micronaut:
  application:
    name: poc

#datasources:
#  default:
#    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: ""
#    driver-class-name: org.h2.Driver
#    min-pool-size: 1
#    max-pool-size: 10

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/poc
    username: poc
    password: poc
    driver-class-name: org.postgresql.xa.PGXADataSource
    #driver-class-name: org.postgresql.ds.PGSimpleDataSource
    min-pool-size: 1
    max-pool-size: 5
  db1:
    url: jdbc:postgresql://localhost:5432/db1
    username: db1
    password: db1
    driver-class-name: org.postgresql.xa.PGXADataSource
    min-pool-size: 1
    max-pool-size: 5
  db2:
    url: jdbc:postgresql://localhost:5432/db2
    username: db1
    password: db1
    driver-class-name: org.postgresql.xa.PGXADataSource
    min-pool-size: 2
    max-pool-size: 4

jpa:
  default:
    compile-time-hibernate-proxies: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

liquibase:
  enabled: true
  datasources:
    default:
      liquibase-schema: liquibase
      change-log: 'classpath:db/poc.changelog.xml'
